# Custom Language File for Launcher Customizer

[ejs.app]
title = "마만추"

[ejs.landing]
mediaGitHubURL = "https://ch.sooplive.co.kr/rlawlsthfw"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/mamanchu"
supportLink = "https://github.com/mchlauncher/mamanchu/issues"

[ejs.welcome]
welcomeHeader = "마만추"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."